# Generated by Django 5.0.7 on 2025-02-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
