# Generated by Django 5.0.7 on 2025-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('fixed', 'Fixed Deposit'), ('offshore', 'Off Shore')], default='savings', help_text='Type of bank account (e.g., Savings, Current, Fixed Deposit)', max_length=20),
        ),
    ]
