# Generated by Django 5.0.7 on 2025-08-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('blocked', 'Blocked')], default='active', help_text='Account status: Active, Disabled, or Blocked', max_length=10),
        ),
    ]
