# Generated by Django 5.0.7 on 2025-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_account_is_active_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.CharField(choices=[('Savings_Account', 'Savings Account'), ('Checking_Account', 'Checking Account'), ('Loan_Account', 'Loan Account'), ('GBP_Account', 'GBP Wallet'), ('EUR_Account', 'EUR Wallet')], default='Savings_Account', help_text='The account selected for deposit', max_length=50),
        ),
    ]
