# Generated by Django 5.0.7 on 2025-08-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_deposit_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='balance',
            field=models.CharField(default='USD', max_length=50),
        ),
    ]
